select wci.addunit('%', 'percent', '%', 1.0, 0.0 );
select wci.addunit('ratio', 'ratio between 0 and 1', '%', 100.0, 0.0 );
select wci.addunit('none', 'no known unit', 'none', 1.0, 0.0 );
select wci.addunit('m', 'metre (SI unit)', 'm', 1.0, 0.0 );
select wci.addunit('mm', 'millimetre', 'm', 0.001, 0.0 );
select wci.addunit('cm', 'centimetre', 'm', 0.01, 0.0 );
select wci.addunit('hm', 'hectometre', 'm', 100.0, 0.0 );
select wci.addunit('km', 'kilometre', 'm', 1000.0, 0.0 );
select wci.addunit('s', 'second (SI unit)', 's', 1.0, 0.0 );
select wci.addunit('ms', 'millisecond', 's', 0.001, 0.0 );
select wci.addunit('min', 'minute', 's', 60.0, 0.0 );
select wci.addunit('h', 'hour', 's', 3600.0, 0.0 );
select wci.addunit('kg', 'kilogram (SI unit)', 'kg', 1.0, 0.0 );
select wci.addunit('C', 'coulumb (SI unit)', 'C', 1.0, 0.0 );
select wci.addunit('K', 'kelvin (SI unit)', 'K', 1.0, 0.0 );
select wci.addunit('mol', 'mole (SI unit)', 'mol', 1.0, 0.0 );
select wci.addunit('cd', 'candela (SI unit)', 'cd', 1.0, 0.0 );
select wci.addunit('rad', 'radian (SI unit)', 'rad', 1.0, 0.0 );
select wci.addunit('m/s2', 'metre per square second (SI unit)', 'm/s2', 1.0, 0.0 );
select wci.addunit('m2', 'square metre (SI unit)', 'm2', 1.0, 0.0 );
select wci.addunit('mol/m3', 'mole per cubic meter (SI unit)', 'mol/m3', 1.0, 0.0 );
select wci.addunit('Pa.s', 'pascal second (SI unit)', 'Pa.s', 1.0, 0.0 );
select wci.addunit('N.s/m2', 'newton second per square metre', 'Pa.s', 1.0, 0.0);
select wci.addunit('kN.s/m2', 'kilonewton second per square metre', 'Pa.s', 1000.0, 0.0 );
select wci.addunit('A', 'ampere (SI unit)', 'A', 1.0, 0.0 );
select wci.addunit('S', 'siemens (SI unit)', 'S', 1.0, 0.0 );
select wci.addunit('V', 'volt (SI unit)', 'V', 1.0, 0.0 );
select wci.addunit('Ohm', 'ohm (SI unit)', 'Ohm', 1.0, 0.0 );
select wci.addunit('J', 'joule (SI unit)', 'J', 1.0, 0.0 );
select wci.addunit('N', 'newton (SI unit)', 'N', 1.0, 0.0 );
select wci.addunit('Hz', 'hertz (SI unit)', 'Hz', 1.0, 0.0 );
select wci.addunit('kg/m3', 'kilogram per cubic metre (SI unit)', 'kg/m3', 1.0, 0.0 );
select wci.addunit('mg/m3', 'milligram per cubic metre', 'kg/m3', 0.000001, 0.0);
select wci.addunit('W', 'watt (SI unit)', 'W', 1.0, 0.0 );
select wci.addunit('W/m2', 'watt per square metre (SI unit)', 'W/m2', 1.0, 0.0 );
select wci.addunit('N/m', 'newton per metre (SI unit)', 'N/m', 1.0, 0.0 );
select wci.addunit('W.s/m2', 'watt second per square metre', 'N/m', 1.0, 0.0 );
select wci.addunit('kW.s/m2', 'kilowatt second per square metre', 'N/m', 1000.0, 0.0 );
select wci.addunit('J/m2', 'joule per square metre', 'N/m', 1.0, 0.0);
select wci.addunit('Pa', 'pascal (SI unit)', 'Pa', 1.0, 0.0 );
select wci.addunit('hPa', 'hectopascal', 'Pa', 100.0, 0.0 );
select wci.addunit('kPa', 'kilopascal', 'Pa', 1000.0, 0.0 );
select wci.addunit('J/m3', 'joule per cubic metre', 'Pa', 1.0, 0.0 );
select wci.addunit('N/m2', 'newton per square metre', 'Pa', 1.0, 0.0 );
select wci.addunit('Pa/s', 'pascal per second (SI unit)', 'Pa/s', 1.0, 0.0 );
select wci.addunit('hPa/s', 'hectopascal per second', 'Pa/s', 100.0, 0.0 );
select wci.addunit('J/kg', 'joule per kilogram (SI unit)',  'J/kg', 1.0, 0.0);
select wci.addunit('m3/kg', 'cubic metre per kilogram (SI unit)', 'm3/kg', 1.0, 0.0 );
select wci.addunit('kg/m2', 'kilogram per square metre (SI unit)', 'kg/m2', 1.0, 0.0 );
select wci.addunit('m/s', 'metre per second (SI unit)', 'm/s', 1.0, 0.0 );
select wci.addunit('m3', 'cubic metre (SI unit)', 'm3', 1.0, 0.0 );
select wci.addunit('deg', 'degree', 'rad', 0.0174533, 0.0 );
select wci.addunit('kg/kg', 'kilogram per kilogram (base proportion)', 'kg/kg', 1.0, 0.0 );
select wci.addunit('m3/m3', 'cubic metre per cubic metre (base proportion)', 'm3/m3', 1.0, 0.0 );
select wci.addunit('/s', 'per second', 'Hz', 1.0, 0.0);
select wci.addunit('K.m2/(kg.s)', 'kelvin square metre per kilogram second (SI unit)', 'K.m2/(kg.s)', 1.0, 0.0 );
select wci.addunit('m2/s', 'square metre per second (SI unit)', 'm2/s', 1.0, 0.0 );
select wci.addunit('kg/(m2.s)', 'kilogram per square metre second (SI unit)', 'kg/(m2.s)', 1.0, 0.0 );
select wci.addunit('sr', 'steradian (SI unit)', 'sr', 1.0, 0.0 );
select wci.addunit('W/(m.sr)', 'watt per metre steradian (SI unit)', 'W/(m.sr)', 1.0, 0.0 );
select wci.addunit('m2/s2', 'square metre per square second', 'J/kg', 1.0, 0.0 );
select wci.addunit('Cel', 'degree celsius', 'K', 1.0, 273.15 );
select wci.addunit('K/m', 'kelvin per metre (SI unit)', 'K/m', 1.0, 0.0 );
select wci.addunit('[in_i]', 'inch', 'm', 0.03, 0 );
