#!/bin/sh

#export DEBCONF_DEBUG=developer
#export dbc_debug=1

. /usr/share/debconf/confmodule
db_version 2.0

if [ -f /usr/share/dbconfig-common/dpkg/config.pgsql ]; then
   . /usr/share/dbconfig-common/dpkg/config.pgsql 
   dbc_go wdb $@

   db_set wdb/user_account "$dbc_dbuser"
   db_set wdb/database_name "$dbc_dbname"
fi
