#!/bin/sh -e

# Source debconf library
. /usr/share/debconf/confmodule

# Get database information
db_get wdb/database_name && DB_NAME="$RET"
db_get wdb/database_admin && DB_USER="$RET"

case "$1" in
    configure)
    	su $DB_USER -c "/usr/lib/wdb/install_remove_old_referencetimes.sh install"
    ;;
    abort-upgrade)
    ;;
    abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
