#!/bin/sh -e

# Source debconf library
. /usr/share/debconf/confmodule

# Get database information
db_get wdb/database_admin && DB_USER="$RET"

case "$1" in
    purge)
		  su postgres -c "psql `wdbConfiguration --psqlArgs` -Upostgres -c 'DELETE FROM clean.strategies WHERE function = \$\$clean_referencetimes\$\$; DROP TABLE clean.referencetime_lifetime; DROP FUNCTION clean.clean_referencetimes()'"  	
	;;
esac

#DEBHELPER#

exit 0
